#+TITLE: Retrospective
* Useful Links
Demos @!(ref "demos")!@.

Weekly Summaries: @!(ref "week07")!@, @!(ref
"week08")!@, @!(ref "week09")!@, @!(ref
"week10")!@, @!(ref "week11")!@, @!(ref "week12")!@.

Full Logs: @!(ref "logs")!@.

Knowledge Graph: @!(ref "dz")!@.
* A Retrospective
Writing style inspired by creative and manic
ramblings of found in the tapestries of Lorina Bulwer
@!(dzref "misc/i_miss_lorina_bulwer")!@.

TO THE NEVER-GRADUATES OF THE RECURSE CENTER BROOKLYN NEW YORK CITY

TO THE NEVER-GRADUATES ACROSS THE PLANET CONNECTED BY WIRES AND ELECTRICITY

I RECURSER PAUL BATCHELOR WAS EXAMINED AND FOUND TO BE A
PROPERLY SHAPED RECURSER FEBUARY THE NINTH TWO
THOUSAND AND TWENTY-FOUR IN ATLANTA GEORGIA SUITABLE
FOR THE SUMMER 1 2024 BATCH. HOPED
TO FIND HIMSELF MAKING THINGS THAT SING AND TALK AND
LAUGH FROM CODE AND MAKE THESE THINGS RUN IN A BROWSER.

PACKED THINGS INTO TINY BOXES AND SHIPPED THEM UP
NORTH MANY BOXES AND THEN I GOT INTO A PLANE AND
WALKED ALONG THE BOSTON COMMON AND SAID HELLO
TO THE SEALS AT THE AQUARIUM FOUR DAYS I WAS IN BOSTON
THEN GOT ON A PLANE TO NEW YORK CITY BROOKLYN.

SHOWED UP IN BROOKLYN MAY THE 19TH ON THE STEPS
OF MY FRIENDS DANS APARTMENT HE LET ME IN AND
LET ME SLEEP ON THE COUCH GOOD FRIEND LONGTIME
FRIEND FRIENDS SINCE WE WERE 3 YEARS AND IN PRESCHOOL
DAN THE REASON WHY I WENT TO RECURSE CENTER WALKED ALONG
THE PARKS AND ENJOYED THE PEOPLE

I RECURSER PAUL BATCHELOR BEGAN HIS BATCH THE TWENTIETH
OF MAY LEARNED A BIT ABOUT EVERYONE FOUND INTERESTING
GROUPS THEN STARTED FIGURING OUT HOW TO WRITE IT ALL
DOWN INTO LOGS.

ON THE THIRD DAY FIRST DAY OF HUB I RECURSER PAUL BATCHELOR
SET FOOT ON THE FOURTH FLOOR SAT ON A COUCH AND OPENED
HIS MACBOOK AIR TO FIND THE SCREEN HAD CRACKED AFTER
MONTHS OF PREP HUNDREDS OF MILES OF TRAVEL NO PROBLEMS
BUT TODAY THE SCREEN DECIDED TO GIVE AFTER A SHORT
TRIP ON THE G LINE A PORTABLE SCREEN WAS USED
INSTEAD AND THIS HELPED OUT A BIT FOR A WHILE BUT
IT WAS A SPRAWL AND TOOK TIME

RUST IS A LANGUAGE THAT IS GOOD FOR AUDIO RELATED THINGS
I RECURSER PAUL BATCHELOR BEGAN WRITING A MONO WAV WRITER
THAT COULD ALLOW ME TO WRITE SOUNDS TO DISK A GOOD
START WROTE THE PROGRAM IN C FIRST THEN PORTED IT TO RUST.

BEGAN BUILDING A VOICE INSIDE THE COMPUTER THE VOICE
STARTS WITH THE VIBRATION OF VOCAL FOLDS CALLED THE
GLOTTIS AND THIS MAKES THINGS BUZZ THEN I CREATED
A VOCAL TRACT A SERIES OF CYLYNDRICAL TUBES FOR THE
BUZZ TO GO INTO THIS MAKES THE VOWELS FOUND SOME NANS
AND THEN BEGAN THE NANHUNT THAT TOOK MANY HOURS TO FIND.

I RECURSER PAUL BATCHELOR WANTED TO USE HIS KNOWLEDGE
OF VOCAL SYNTHESIS TO EXPLORE WEBAPPS AND RUST AND
WEBASSEMBLY AND WEBAUDIO STARTED OUT BY MAKING A PROTOTYPE
USING JAVASCRIPT WEBAUDIO AND SLIDERS TO CONTROL THE HUMAN
VOICE IT WAS A VERY HELPFUL THING.

MOVED AGAIN CLOSER TO THE HUB THIS TIME VERY CLOSE ALSO
CLOSER TO A TRADER JOES AND A TARGET NEVER BEEN SO CLOSE
TO A TARGET ALSO A WHOLE FOODS AND AN APPLE STORE EVERYTHING
IS CLOSE BY EVERYONE WALKS AND MOVES AT THE SPEED OF
WALKING WITH SOME TRAINS IN BETWEEN THIS IS HOW IT SHOULD BE.

STARTED READING ABOUT REACT THEY SAID TO LEARN TYPESCRIPT
AS WELL BUILT MY PROTOTYPE AGAIN IN TYPESCRIPT THANK YOU
FOR SHOWING ME HOW TO DO THIS THEN I WANTED TO BUILD SOMETHING
MORE MUSICAL SOMETHING WITH MORE THAN ONE VOICE. TUNED
FOUR VOICES TOGETHER TO MAKE IT BLEND MAKE IT FEEL
REAL THEN I PUT IT IN A WEB APP AND CALLED IT VOCAL CHORDS
AND SHOWED IT AT HALFBAKED DEMOS WHERE THEY TOLD ME
MY VOICE WAS DROWNED BY THE CHOIR OF ELECTRONIC ANGELS

I RECURSER PAUL BATCHELOR GOT A REFURBISHED X390
TO REPLACE MY
M1 MACBOOK AIR TWAS THE CHEAPER OPTION AND KEYS FEEL
GOOD TO TYPE ON AND I ENJOY RUNNING LINUX JUST LIKE
THE BOX AT HOME. REDISCOVERED THE JOY OF USING WACOM
TABLETS TO SHAPE SOUND GOT A SMALL TABLET USED LIBEVDEV
TO CONTROL THINGS IN C WITH DSP IN RUST.

CREATURE SOUNDS ARE HARD BUT ATTEMPTED TO BUILD ONE
WHERE YOU COULD POKE A CREATURE AND IT WOULD LAUGH
BUT IT DIDN'T REALLY LAUGH AND THIS MADE MANY PEOPLE
SAD SO I WAS SAD BUT IT WAS A GOOD LESSON.

NAND2TETRIS COMPUTER ENGINEERING WAS INTERESTING SO
PICKED UP THE ELEMENTS OF COMPUTER SYSTEMS READ THE FIRST
SIX CHAPTERS LEARNED ABOUT LOGIC GATES NAND HARDWARE
DESCRIPTION LANGUAGES ASSEMBLY ALSO PICKED UP SOME
GAMEBOY ASSEMBLY PROGRAMMING ATTEMPTING TO GET SOUNDS
FROM A GAMEBOY FOR MY SECOND IMPOSSIBLE DAY IN MY BATCH.

I RECURSER PAUL BATCHELOR KNOW UNIX SYSTEMS AND BECAUSE
OF THIS I WAS ABLE TO USE A NEXT COMPUTER TERMINAL
DESPITE NEVER TOUCHING A NEXT COMPUTER TERMINAL BEFORE.

INSPIRED BY VOICES THREE VOICES IN A SPACE WITH
GLISTENING STAGGERED HARMONIES STREWN OUT OVER TIME WITH
INTERMEDIATE VOICES CLASHING TOGETHER BUILT AN APPLICATION
WHERE YOU WERE OFTEN NOT ALONE TWO VOICES AND UPPER VOICE
AND AN LOWER VOICE WOULD WAKE UP AND FOLLOW YOU AROUND
AND THIS WOULD CREATE TRIADIC HARMONY USING CHORD SELECTION
HEURISTICS I WROTE. DEVELOPED ALL IN RUST PROTOTYPED ON THE
TRACKPAD THEN PORTED TO WEBASSEMBLY WITH JAVASCRIPT AND
CANVAS AND I CALLED IT TRIO AND PRESENTED IT TO AN AUDIENCE
ON A THURSDAY THEN

I RECURSER PAUL BATCHELOR WOKE UP UP EARLY SAT EVERY DAY
AT THE SAME SPOT ON THE TABLE WANTED TO BE INTERRUPTED
AND WAS INTERRUPTED IN AMAZING WAYS.
