#+TITLE: Week 11

* Saturday, July 27th

Logs: @!(ref "logs" "logs" "2024_07_27")!@

Audio Telephone Composition.

* Sunday, July 28th

Logs: @!(ref "logs" "logs" "2024_07_28")!@

Tasks: @!(taskref "demo-trio")!@, @!(taskref "demo-trio-chords")!@.

* Monday, July 29th
Logs: @!(ref "logs" "logs" "2024_07_29")!@

Tasks: @!(taskref "demo-trio-chords")!@, @!(taskref "demo-trio-web")!@.

More Trio work.

I sketched out a new way to think about chord
changes ("committing chords") that should make
the chords more coherent.

I did an initial attempt to port stuff to the web.
Got side-tracked. Attempted to use Typescript with p5.
It didn't go well. I'm going to start from scratch
(again).

* Tuesday July 30th
Logs: @!(ref "logs" "logs" "2024_07_30")!@

Tasks: @!(taskref "demo-trio-web")!@.

Spent the better part of the day just trying to
get Trio ported to the web. First time using
the Canvas API directly (insteading of using
something like p5).

Lots of weird troubleshooting with WebAudio stuff.
It is a very opaque API to deal with. Also,
mobile feels like flying blind without seeing
any logs. Fortunately, Google still works well
enough to look up vague things like "why is my
pointer only moving a little bit on chrome?"

* Wednesday July 31st
Logs: @!(ref "logs" "logs" "2024_07_31")!@

Tasks: @!(taskref "demo-trio-web")!@.

Got Trio published as a demo.
