#+TITLE: Week 10

* Saturday, July 20th

Logs: @!(ref "logs" "logs" "2024_07_20")!@

DAG Zettelkasten /
generates database code /
more will come later

Tasks: @!(taskref "dagzet-rust")!@

It was pretty much an entire day spent
on my dagzet rust port. I got loop checking
to work in the morning, and the some
initial SQLlite generation code made
later.

Most of the time I think was spent trying
to be clever with Rust's type system. I
wanted there to be a way to use structs
as an intermediate representation for
a row of a particular table. You send
this row struct as an argument into
a method on a table struct, and you'd
have the type checker ensure that only
that particular kind of row works with
that particular kind of table. It was
a top-down idea, rather than a bottoms-up
one in the sense that I knew what I
wanted the programming interface to feel
like, and it was a matter of wrangling
Rust to do it for me. The solution ended up
using a combination of traits, generics,
and things called "phantom types" and  "phantom data".
See: @!(dzref "rust/phantom_types")!@

@09:46 Which commands am I using in my recurse dagzet? #dagzet-rust
The goal is to get just enough working that it can replace
my RC dagzet. I believe I can do this with just some shell
scripts.

* Sunday, July 21st

Logs: @!(ref "logs" "logs" "2024_07_21")!@

Tasks: @!(taskref "dagzet-rust")!@

I really only worked in the morning
yesterday. Managed to scope out the bare minimum
of what needs to be done in order for my dagzet
rust port to work with my existing RC knowledge
graph. It is, of course, more work than I expected

* Monday, July 22nd

Logs: @!(ref "logs" "logs" "2024_07_22")!@

Tasks: @!(taskref
"demo-trio-voice-scheduler")!@, @!(taskref "dagzet-rust")!@

Pretty much most of my day was spent building up
a new voice scheduling system for the Trio
demo @!(taskref "demo-trio")!@. The idea was to build
a system that made it easy to simulate interactions
in a test suite to ensure that behavior in the
system was working correctly.

Dan showed me Stately @!(dzref "webdev/stately_docs")!@, because I mentioned
my interested in building a state machine
representing this system.

Dagzet in Rust is chugging along. I didn't do
much yesterday, but I did implement the rest of
the File Range command. I still need to generate
the table for it (this should be a small task).

* Tuesday, July 23rd

Logs: @!(ref "logs" "logs" "2024_07_23")!@

Tasks: @!(taskref "dagzet-rust")!@, @!(taskref "demo-trio-voice-scheduler")!@, @!(taskref "demo-trio")!@.

Yesterday I achieved some good milestones for both
dagzet and Trio.

The big job I've been doing with Trio is to do a complete
rewrite of the voice scheduling system, complete with
a set of tests to ensure the behavior is working
correctly.

The initial work has been
completed and integrated into the actual Trio system.
It mostly works. There is one timing bug I don't
quite understand: The lower voice sometimes
waits one beat too long before turning on. I also
fixed some code related to my event scheduler.

I am nearly done implementing the initial command
set for my Rust port of Dagzet. I forgot about
the "cx" command though. As a test, I tried to use
it to generate my knowledge graph, and ran into
some issues. I'm going to need more descriptive
errors in the command line before I can figure
out what is going on.

