#+TITLE: Week 8
* Saturday, July 6th
@!(ref "logs" "logs" "2024_07_05")!@

kickstart neovim /
slider groups typescript react /
rust-analyzer

** Neovim setup
task: @!(taskref "investigate-kickstart-neovim")!@.

Got a neovim setup working with kickstart,
language server works for both Rust (rust-analyzer) and
Typescript (typescript-nvim). Learned a little bit
about installing plugins with neovim.
** React + Typescript: UI progress and porting webaudio bits
tasks: @!(taskref "demo-react-UI")!@, @!(taskref "how-big-are-react-apps"!@.

I've been trying to find excuses to learn React,
and now with suggestions from others, I'm learinng
Typescript too. So, I've been porting 

Spent time writing more
abstractions to match the slider groups in 
my singer UI. Did some initial work trying to get
the webaudio JS code ported to typescript.

Also, learned how to export npm projects to minified
JS. The total size of this app so far is 600kb, compared
to the 12kb for my vanilla JS demo. A little bit yikes,
but not unexpected. It is what it is.
** TeX backend for resume generator
I've been yak-shaving my resume by building a
new resume generator (as is tradition). I had
an older CV I wrote using plain TeX (yup, just
TeX, not LaTeX, because reasons), and used that
to build a TeX backend. Now my resume has a markdown
and TeX, and the markdown can be converted to HTML
via pandoc.
