#+TITLE: Week 7

* Saturday, June 29th

@!(ref "logs" "logs" "2024_06_29")!@

Typescript and React /
Topological Sort Bugs /
Singing Quite Loudly

* Sunday, June 30th

@!(ref "logs" "logs" "2024_06_30")!@

The creeping answer /
Of a gigantic bug hunt: /
Check for foreign nodes.

* Monday, July 1st

Poking Propulsion /
Works better in Chromium /
Stored State in Sliders

* Tuesday, July 2nd

Tiny Creature Sounds /
Told Told Some People About It /
Then I learned about Zig

Iinitial Creature Sounds (morphing a sequence of tube
shapes), Audio Chats with Dan,
Webdev Hangout (spatial audio, typescript stuff,
frog choir), tested out MIDI controller.

* Wednesday, July 3rd

built jitter signals /
summer 2 conversations /
learned about old pipes

implemented jitter and jitter components (RandomLine,
RandomPhasor), implemented ordered lists, lots of
conversations with the summer 2s, more resume structure
in dagzet (yak shaving), added links to @!(ref
"demos")!@ page, attempt to figure out text templates
in Go (again, more yak shaving for resume,probably not worth
my time actually).

* Thursday, July 4th

sounds and visuals /
connected together for /
the poking demo

Worked out poking mechanics for sound, hooked up
initial audio and sound. Chatter sound refactored
to live inside single struct (better for porting). figured out
"tap to begin" mechanic to start webaudio. Created envelope
generator, triggergate, metro.
