javascript/IIFE	1	0
javascript/coercion	1	1
javascript/instanceof	1	0
javascript/rest_parameter	1	2
javascript/this	1	0
webdev/single_responsibility_principle	1	2
webdev/typescript/conditional_types	1	0
webdev/typescript/covariance_contravariance	1	0
webdev/typescript/discriminated_union	1	0
webdev/typescript/excess_property_checking	1	0
webdev/typescript/generic_constraint	1	0
webdev/typescript/generic_parameter_default	1	0
webdev/typescript/identity_function	1	0
webdev/typescript/implementation_signature	1	1
webdev/typescript/indexed_access_type	1	1
webdev/typescript/infer	1	1
webdev/typescript/keyof	1	0
webdev/typescript/overload_signature	1	1
webdev/typescript/typeof	1	0
